require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 35

Layout/HashAlignment:
  EnforcedColonStyle: table

RSpec/DescribeClass:
  Enabled: false
