name: Ruby

on: [push]

jobs:
  build:
    name: "Run Rspec Tests"
    env:
      PUPPET_GEM_VERSION: "~> 7.24.0"
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: 2.7.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake spec
